version: '3.8'

services:
  secure-nginx:
    image: nginx:latest
    container_name: secure-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge